name: Frontend CI/CD Pipeline

on:
  push:
    branches: [ "main", "refactor/user-view" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Continuous Integration (CI)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Project
      run: npm run build -- --configuration=production

  deploy:
    name: Continuous Deployment (CD)
    needs: build
    runs-on: [self-hosted, deportivo-ucn-frontend]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/refactor/user-view'

    steps:
    - name: Checkout Code on VM
      uses: actions/checkout@v4

    - name: Restart Docker Containers
      run: |
        docker compose down
        docker compose up -d --build
